### ISSUE TITLE
Recent builds do not include the new user manual

### ISSUE THREAD

**Issue by polwel** [Tey/speedcrunch-nightlies#1]
The builds since the merge of the new user manual feature do not include the latter. The window simply stays blank. You probably need to have a look at your build system.

Thanks!

**Comment by Tey** [comment]
Thanks for the report. [I'm aware of that problem](https://github.com/Tey/speedcrunch-nightlies/commit/f58a8be835421b4c8fc2f1b8bfba9af71b7e851f) but don't have the time to investigate it yet :( It already took me too much time to make the building process work again after the merge of the manual PR.

That's also why I still haven't answered your PR and issue about the evaluator. Sorry about that.

**Comment by polwel** [comment]
Yes, as you might have heard we are seriously considering to separate 
the manual's build process from the application's. So don't waste too 
much time on this now :)

About the recursion thing: No problem, take your time :) We are not in a 
hurry.

**Comment by Tey** [comment]
Should be fixed now.
