### ISSUE TITLE
Add user-defined constants

### ISSUE THREAD

**Issue by Shindanaide** [Tey/speedcrunch-nightlies#3]
It would be very useful to add custom constants that remain between sessions.

**Comment by Tey** [comment]
This repository is only here for hosting SC binaries. Please, use the [official repository](https://bitbucket.org/heldercorreia/speedcrunch/) for filling tickets.

As for your suggestion, it is already possible using [user variables](http://speedcrunch.org/userguide/advanced.html#variables).
